In [2]:
import numpy as np

In [119]:
N = 10
x = np.arange(N)
M = x[::-1]
M

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [124]:
y = np.diag(M)
np.trace(y)

45

In [136]:
a = np.array( [ [4,2,1], [1,3,0], [0,5,4]])

In [137]:
b = np.array( [4,12,-3] )

In [140]:
from numpy import linalg

In [142]:
linalg.solve(a,b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [153]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
users_stats

array([[2, 1, 0, 0, 0, 0],
       [1, 1, 2, 1, 0, 0],
       [2, 0, 1, 0, 0, 0],
       [1, 1, 2, 1, 0, 1],
       [0, 0, 1, 2, 0, 0],
       [0, 0, 0, 0, 0, 5],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1, 3],
       [1, 0, 0, 2, 1, 4]])

In [154]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])
next_user_stats

array([0, 1, 2, 0, 0, 0])

In [158]:
ScalarA = np.dot(users_stats,next_user_stats)
ScalarA

array([1, 5, 2, 5, 2, 0, 0, 3, 0, 0])

In [176]:
Length_users_stats = np.linalg.norm(users_stats)
Length_users_stats

9.539392014169456

In [178]:
Length_next_user_stats = np.linalg.norm(next_user_stats)
Length_next_user_stats

2.23606797749979

In [180]:
Length = Length_users_stats*Length_next_user_stats
Length

21.330729007701542

In [181]:
Similar = ScalarA/Length
Similar

array([0.04688072, 0.23440362, 0.09376145, 0.23440362, 0.09376145,
       0.        , 0.        , 0.14064217, 0.        , 0.        ])

In [187]:
Similar_shoper = np.where(Similar == max(Similar))[0]+1
print("Самые похожие покупатели под номером/ми - " , Similar_shoper)

Самые похожие покупатели под номером/ми -  [2 4]
